### ISSUE TITLE
Seeker Profile

### ISSUE THREAD

**Issue by AliTarek99** [AliTarek99/Recruitment-Management-Platform-Backend#17]
Ali FINISHED
get profile /seekers/profile 
 put edit profile /seekers/profile 

Salah FINISHED
 get experiences /seekers/experience 
 post add experience /seekers/experience 
 put edit experience /seekers/experience 
 delete experience /seekers/experience 

Omar
   get education /seekers/education
   post add education /seekers/education
   put edit education /seekers/education
   delete education /seekers/education

Abdo  FINISHED
   get cvs /seekers/cvs (if a recruiter or company is viewing, get the CV that the seeker applied with to the job (candidate CV))
   get cv file /seekers/cvs
   delete cv /seekers/cvs
   get skills /seekers/skills 
   post add skill /seekers/skills 
   delete skill /seekers/skills

**Comment by AliTarek99** [comment]
> add get seeker image endpoint

Done

> Add company id in seeker experience table

Done

**Comment by omarfarouk311** [comment]
Produce into profile embedding generation topic when the user changes experience, education, or skills

**Comment by omarfarouk311** [comment]
> Produce into profile embedding generation topic when the user adds or changes experience, education, or skills

The education and experience message production is still not implemented
@omaradwan @Abdelrahman034
